.TH SWIPROLOG 1 "12 December 2001"
.SH NAME
swiprolog \- deprecated name of SWI-Prolog
.SH DESCRIPTION
\fBswiprolog\fP is the name that previous Debian packages of SWI-Prolog used
for the binary. It is now \fBswipl\fP(1) to comply with upstream naming.
.PP
Upstream likes to call the binary \fBpl\fP, but this was changed in Debian
because of name space pollution. Alternatives listed in the manual are
\fBswipl\fP and \fBswi-prolog\fP, of which the former was chosen for its
terseness.
.SH SEE ALSO
.BR swipl (1).
.SH AUTHOR
SWI-Prolog was written by Jan Wielemaker <jan@swi.psy.uva.nl> and others.
.PP
This manual page was written by Michael Piefel <piefel@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
